---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dra-rt-driver.fullname" . }}-role
  namespace: {{ include "dra-rt-driver.namespace" . }}
rules:
- apiGroups:
  - ""
  - resource.k8s.io
  - rt.resource.example.com
  - nas.rt.resource.example.com
  - metrics.k8s.io
  resources: ["*"]
  verbs: ["*"]
