# Two pods, one container each
# Each container asking for 1 distinct GPU

---
apiVersion: v1
kind: Namespace
metadata:
  name: rt-test1

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: rt-test1
  name: rt.example.com
spec:
  spec:
    resourceClassName: rt.example.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: rt-test1
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: rtcpu
  resourceClaims:
  - name: rtcpu
    source:
      resourceClaimTemplateName: rt.example.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: rt-test1
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: rtcpu
  resourceClaims:
  - name: rtcpu
    source:
      resourceClaimTemplateName: rt.example.com
