# Two pods, one container each
# Each container asking for 1 distinct GPU

---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: rt11

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  namespace: rt11
  name: rt.example.com
spec:
  spec:
    resourceClassName: rt.example.com
    parametersRef:
      apiGroup: rt.resource.example.com
      kind: RtClaimParameters
      name: rtclaims

---

apiVersion: rt.resource.example.com/v1alpha1
kind: RtClaimParameters
metadata:
  namespace: rt11
  name: rtclaims
spec:
  count: 2
  runtime: 1000
  period: 1000000

---
apiVersion: v1
kind: Pod
metadata:
  namespace: rt11
  name: pod0-1
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: rtcpu
  - name: ctr1
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: rtcpu1
  resourceClaims:
  - name: rtcpu
    source:
      resourceClaimTemplateName: rt.example.com
  - name: rtcpu1
    source:
      resourceClaimTemplateName: rt.example.com

---